### ISSUE TITLE
request returns javascript

### ISSUE THREAD

**Issue by 0gordonfreeman** [szkkteam/bot-house-find#1]
Hi,

thanks for your great work. i tried your bot local on my windows bash integration but it was not working for me.
i added a debug to get the content of the response:
`2022-04-17 08:16:45.010 | DEBUG    | __main__:get_url:73 - Opening URL: 'https://www.willhaben.at/iad/immobilien/grundstuecke/steiermark/weiz?areaId=6&page=24&rows=100&view='.
2022-04-17 08:16:45.099 | DEBUG     | __main__:get_url:76 - response: 'b'<html><head><script type="text/javascript"></script></head>\n<body onload="go()">\nLoading...\n</body>\n</html>\n''
''
`

It looks like that they have a added a bot check. 
Do you also experience this issue or is this maybe a problem because of my environment?

kind regards,
Max

**Comment by szkkteam** [comment]
Hi,

I haven't used this script in the last couple of years, it's possible they
implemented some features to prevent scrapping. I won't be front of my PC
in the next few days, but I will check what could be the issue.

Kind regards
Szkk

**Comment by szkkteam** [comment]
Hi, quickly checked what could be the issue, and looks like they changed the frontend completely. Previously they used SSR but now they are using CSR. The response for the first request is an "empty" HTML file, therefore the script should execute javascript to render the page. This script should be completely reworked to use Selenium or a similar engine. Feel fee to fork and update it according to your needs.

**Comment by szkkteam** [comment]
Hi, quickly checked what could be the issue, and looks like they changed the frontend completely. Previously they used SSR but now they are using CSR. The response for the first request is an "empty" HTML file, therefore the script should execute javascript to render the page. This script should be completely reworked to use Selenium or a similar engine. Feel fee to fork and update it according to your needs.

**Comment by 0gordonfreeman** [comment]
thanks for you analysis. it would be great if you update your script. i'll also give it a try but i don't have any experience with selenium for now.
